### ISSUE TITLE
Scripted dialogue format needed

### ISSUE THREAD

**Issue by wsowens** [ufosc/MuddySwamp#10]
We need a robust format for an executable dialog format. The key features it should support are:
- messaging blurbs of text to the player
- listing choices to the player, and waiting for a reply
- linking actions to specific choices; ex:
  - unlock door
  - spawn dragon
  - increase player's health
  - give the player an item
- making some choices only offered under certain conditions, ex:
  - if the player is a certain class
  - if the player is in a faction
  - if a dragon is already in the current location
  - if this player has already selected this dialog option
- making some responses / actions occur under certain conditions

Moreover, this format should emphasize:
- modularity
- readability
- ease of writing

We want people who aren't necessarily familiar with the deeper parts of the engine, to still be able to write scripted dialogue interactions. That said, it would be nice if more advanced users could plug direct engine code (python) into a dialog script (if desired).

**Comment by wsowens** [comment]
The current format that I have proposed is something like this:
```
Hello, I am the gatekeeper Golden City, what do you need?
-  Can you unlock the gate?
    `if Player in golden_city_faction.members:`
        Sure!
        `gate.is_locked = false`
    `else:`
        Scram, outsider.
        - Wait! I am worthy!
            `if self.level > 10:`
                On second thought, we'd be honored to have you in our city.
            `else:
                That's gonna be a no from me dog. 
        - [Walk away]
            `return`
- [Walk away]
    `return`
```
That said, I would love to see what other people have to offer.

**Comment by anth01ogy** [comment]
Do we have a format for defining [Walk away] and other actions?

**Comment by wsowens** [comment]
No. When I said "[walk away]", that's just to signal to the player that this choice will terminate the conversation. With the format I proposed, however, provide more direct actions like so:
```
Your mother was a goose and your father smelt of elderberries.
- Really now, care to back those words up with a blade? [Attack]
   `speaker.isHostile = True`
- [Say nothing and leave the conversation]
   `return`
- How dare you! Good day to you, sir! [Leave the room]
   `#finding the first available exit`
   `for exit in speaker.location.exit_list():
        `player.cmd_walk(exit.name)`
        `break`
```
With my proposed format, any action can just be scripted in python code. However, I think this does affect the learning curve for writing dialog, so I think a more basic approach could also work here.

**Comment by wsowens** [comment]
I have a working parser for the rudimentary format that I described above.

Yet with ANTLR4, I think that we could potentially design a super easy to read scripting language of our own.  Any thoughts?

**Comment by wsowens** [comment]
Moved to low-priority; dialogue / NPCs are not going to be supported for V1

**Comment by wsowens** [comment]
Closing for now, may be reopened at a later date.
