### ISSUE TITLE
Broadcast command no longer working

### ISSUE THREAD

**Issue by wsowens** [ufosc/MuddySwamp#19]
The server administrator command `broadcast` is no longer working. I suspect this is because of the new way players are managed. Ideally, `broadcast` should send the provided message to all Receivers on the server.

As you can see from the client (right window), no message is received.
![issue](https://user-images.githubusercontent.com/22205370/46970285-af4c2c00-d086-11e8-93fc-9b64511e0d45.png)

Implementation is not a concern here.

**Comment by gageowe** [comment]
players command doesn't seem to be working either
