### ISSUE TITLE
Confirmation of successful command inputs using debug mode

### ISSUE THREAD

**Issue by chlolol** [ufosc/MuddySwamp#21]
I feel like it would provide more clarity to the project if it simply printed out a "Success!" or, "command not found" kind of line whenever a server command is made, if a "debug mode" is set to true. If there is a bug on the character side, (like with the broadcasting issue), and new people are messing with the program, then they know for sure that the command executed.

**Comment by wsowens** [comment]
This issue got overlooked during last semester, but both versions on develop and master inform the user when a command is not recognized.
