### ISSUE TITLE
Remove any tabs used in user-directed output

### ISSUE THREAD

**Issue by wsowens** [ufosc/MuddySwamp#25]
Refer to the image below:

![image](https://user-images.githubusercontent.com/22205370/52028515-4e355080-24dd-11e9-930b-73959544d2ee.png)

The help menu looks atrocious because this client does not render tabs as expected. 
We should not include the tab character in user-directed outputs so that we may ensure a consistent experience for the users. 

We should set a standard (2 spaces? 4 spaces?) that we follow for any client-side indentation. We could also make a "TAB" global in character.py and use that.

Discussion is welcome below.

**Comment by pankeleo** [comment]
I replaced a "\t" with a TAB var in util that contains 4 spaces
