### ISSUE TITLE
Update cmd_look

### ISSUE THREAD

**Issue by wsowens** [ufosc/MuddySwamp#29]
By default, the player receives no information when they walk in a room.

This is undesirable for a few reasons. First, we want users to know the contents of a room the moment they walk in. However, we don't want to blast users with a location's description every time they walk in.

Here is an ideal outcome:
```
> walk bathroom
You see Bill the Dark Wizard and Leo the Dark Wizard.
You see a sword on the ground.
Exits Available: exit: Marston Basement, stall: Basement Stall

> look
A paper towel dispenser precariously hangs from the wall. You notice one stall has a strange green
glow emanating from it.

You see Bill the Dark Wizard and Leo the Dark Wizard.
You see a sword on the ground.
Exits Available: exit: Marston Basement, stall: Basement Stall
```
This means less typing for our users. Moreover, we can eventually let `look` take arguments:
```
> look sword
Rusty Sword: Damage 10, Value 3
and if we add entities to the game:
> look paper towel dispenser
The paper towel dispenser appears to have something inside.
```

Implementation details are not as important here, but the function that builds the "current stats" for the location...
```
You see Bill the Dark Wizard and Leo the Dark Wizard.
You see a sword on the ground.
Exits Available: exit: Marston Basement, stall: Basement Stall
```
...should be located in `location.py`. Feel free to modify `__str__` in the location class. 

When a player calls look, they get the location's description and "current stats". When I player enters a location, they should *only* get the "current stats".

**Comment by awhigham9** [comment]
I'll work on it. I was thinking I could add a verbose parameter, and have cmd_walk have a verbose=false cmd_look call embedded within it. I'll probably experiment with adding arguments too, but that's more preliminary.

**Comment by wsowens** [comment]
I like the idea of having a verbose parameter, but maybe add it to Character.set_location instead of `cmd_walk`?

**Comment by awhigham9** [comment]
Yep, that'd be better

**Comment by wsowens** [comment]
This was completed and merged into develop.
