### ISSUE TITLE
Add more testing locations to locations/

### ISSUE THREAD

**Issue by wsowens** [ufosc/MuddySwamp#3]
Locations should follow the .json format described in [locations/template.txt](https://github.com/ufosc/MuddySwamp/blob/develop/locations/template)

These locations are not intended to be final, and as the setting changes, we probably delete some and update others. We mostly just need to rigorously test the Location navigation and parsing system.

**Comment by xeranimus** [comment]
hey, Will, I added some locations on [whatever-branch]
