### ISSUE TITLE
Should we change cmd_walk to be cmd_go?

### ISSUE THREAD

**Issue by wsowens** [ufosc/MuddySwamp#30]
Do we want to make assumptions about characters' modes of locomotion? Typing `walk` could break immersion for anyone playing as a slug person.

To be more pragmatic: having to type 2 fewer characters could add up tremendously over time.

**Comment by pankeleo** [comment]
Yeah I can agree with that

**Comment by wsowens** [comment]
This was made official and merged into develop.
