### ISSUE TITLE
Convert all commands to new-style commands

### ISSUE THREAD

**Issue by awhigham9** [ufosc/MuddySwamp#41]
Currently, there is both a mix of old-style and new-style commands in throughout the code base, with old-style commands predominating. The new style of writing commands is more reusable, modular, and intuitive.

An old-style command is written as follows, within the Character class or one of its subclasses:
```
def cmd_foo(self, *other_params*, args):
    # Do something
```

All old style commands' method signatures begin with "cmd_". This is required because the command dictionary (for a Character instance, self.cmd_dict()) is written so that methods beginning with "cmd_" are added the users dictionary under the name of the substring after "cmd_" in the method signature. Then the user would call it by typing this substring to the console. For example, for the above command a user would type "foo" followed by any necessary arguments.

New-style commands, instead, use decorators to accomplish a similar class. The previous command written in the new style might look like:
```
import command

class someCharacterClass:
    # Other Functions

   @command.class_command
    def foo(self, *other_params*, args):
        # Do something
```
The decorator @command.character_command is invoking a hypothetical function in command.py. This might look like:
```
def class_command(func):
    return Command(func.__name__, func, "Class", )
```

For more examples of writing new-style commands, see entity.py and entitytest.py.

All commands should be converted to this style. This will require creating all decorators and the corresponding higher order function calls, as well as all necessary new classes for specific command types.

Relevant files: command.py, character.py, subclasses of character.py

**Comment by wsowens** [comment]
We will probably have to define a new class, Character.CharCommand, add the accompanying decorator, and change-up the logic of the CharacterClass meta. 

So, are we 100% ditching the cmd_ syntax, or should we have some backwards compatibility?

**Comment by wsowens** [comment]
As of 7e2e08295809209f209fb5bb47aa73efa1d7d203, the `command` module was refactored and all default commands were replaced with the new style of commands. Prefixing commands with 'cmd_' is no longer supported.
